[package]
name = "doc_intel"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.13.0"
file_type = "0.8.11"
futures-util = "0.3.32"
lopdf = "0.40.0"
pdf-extract = "0.10.0"
reqwest = { version = "0.13.3", features = ["json"] }
serde_json = "1.0.149"
tokio = "1.52.3"
uuid = "1.23.1"
